# Generated by Django 4.0.6 on 2022-08-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('domain', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=15)),
                ('mail', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='images/')),
                ('education', models.TextField()),
                ('skill', models.TextField()),
                ('about', models.TextField()),
                ('hobby', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
    ]
