# Generated by Django 4.0.6 on 2022-08-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_collection_cgpa_collection_college_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='mail',
            field=models.TextField(),
        ),
    ]
