# Generated by Django 4.0.6 on 2022-08-21 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_collection_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='education',
        ),
    ]
